name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions: read-all

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gradle-version: ['current', '8.12.1', '7.6.4']
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version-file: .java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{ matrix.gradle-version }}

      - name: Compile classes
        run: ./gradlew classes testClasses --continue

      - name: Lint
        run: ./gradlew detektMain detektTest --continue

      - name: Check
        run: ./gradlew check --continue

      - name: Verify Dependencies
        run: ./gradlew buildHealth
