name: Trigger Snapshot Release

on:
  push:
    branches:
      - main

jobs:
  publish_archives:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true

      - name: Verify build
        run: ./gradlew check

      - name: Publish the artifacts
        run: ./gradlew publishPlugins --no-configuration-cache
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
